// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_DrawingWidget.cpp"
#include "EWIEGA46WW/moc_EventHandling.cpp"
#include "EWIEGA46WW/moc_MenuInit.cpp"
#include "EWIEGA46WW/moc_MenuMain.cpp"
#include "EWIEGA46WW/moc_MyCAD.cpp"
#include "EWIEGA46WW/moc_Shape.cpp"
#include "EWIEGA46WW/moc_ShapeCircle.cpp"
#include "EWIEGA46WW/moc_ShapeLine.cpp"
