name: Build MyCAD on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Set up Qt
        uses: jurplel/setup-qt-action@v2
        with:
          version: '6.8.0'
          architecture: x64
          target: 'win64-msvc2022'

      - name: Check Qt6_DIR
        run: echo "Qt6_DIR is set to: $env:Qt6_DIR"

      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$env:Qt6_DIR" -B ${{ github.workspace }}/build -S ${{ github.workspace }}/MyCAD

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release
