name: Build MyCAD

on:
  push:
    branches:
      - master
    tags:
      - "v*"  # Запуск при пуше тега

  pull_request:
    branches:
      - master

permissions:
  contents: write  # Даем доступ к созданию релиза и "Workflow permissions" -> Read and write permissions.

jobs:
  # Сборка для Windows (Release)
  win:
    runs-on: windows-latest

    steps:
      # Ваши шаги для сборки Windows
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install latest aqtinstall
        run: python -m pip install --upgrade aqtinstall
      - name: Install Qt 6.8.0
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.0'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: true
      - name: Configure CMake (Release)
        run: cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="%Qt6_DIR%" -B ${{ github.workspace }}/build -S ${{ github.workspace }}/MyCAD
      - name: Build (Release)
        run: cmake --build ${{ github.workspace }}/build --config Release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/MyCAD.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Сборка для Windows (Debug)
  win_debug:
    runs-on: windows-latest

    steps:
      # Ваши шаги для сборки Windows Debug
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install latest aqtinstall
        run: python -m pip install --upgrade aqtinstall
      - name: Install Qt 6.8.0
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.0'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: true
      - name: Configure CMake (Debug)
        run: cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="%Qt6_DIR%" -B ${{ github.workspace }}/build_debug -S ${{ github.workspace }}/MyCAD
      - name: Build (Debug)
        run: cmake --build ${{ github.workspace }}/build_debug --config Debug
      - name: Create Debug Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_debug_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-debug
          name: Debug Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Debug Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build_debug/Debug/MyCAD.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Сборка для Ubuntu (Release)
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Qt 6.8.0
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-qmake
      - name: Configure CMake (Release)
        run: |
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/opt/qt6/lib/cmake/Qt6" -B ${{ github.workspace }}/build -S ${{ github.workspace }}/MyCAD
      - name: Build (Release)
        run: cmake --build ${{ github.workspace }}/build --config Release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/MyCAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Сборка для Ubuntu (Debug)
  ubuntu_debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Qt 6.8.0
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-qmake
      - name: Configure CMake (Debug)
        run: |
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="/opt/qt6/lib/cmake/Qt6" -B ${{ github.workspace }}/build_debug -S ${{ github.workspace }}/MyCAD
      - name: Build (Debug)
        run: cmake --build ${{ github.workspace }}/build_debug --config Debug
      - name: Create Debug Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_debug_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}-debug
          name: Debug Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Debug Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build_debug/Debug/MyCAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# Проблема в том, что тег v1.0.0 уже существует, но не был изменен.

# 1. Удаление старого тега
#Сначала удаляем локальный и удаленный тег:

# git tag -d v1.0.0  # Удаляем локальный тег
# git push origin --delete v1.0.0  # Удаляем тег из удаленного репо
# 2. Создание нового тега

# git tag -a v1.0.0 -m "Release version 1.0.0"
# git push origin v1.0.0


# Когда вы вносите изменения в код и хотите отправить их в удаленный репозиторий, вам нужно выполнить команду:
# git push origin master
# Эта команда отправляет изменения из вашей локальной ветки master в удаленный репозиторий.
# Для создания и отправки нового тега:

# Когда вы хотите создать новый релиз или тег, например, для версии программы, нужно:
# Сначала создаете тег:

# git tag -a v1.0.1 -m "Release version 1.0.1"
# Затем отправляете его в удаленный репозиторий:
# git push origin v1.0.1