name: Build MyCAD on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set Qt path
        run: echo "Qt6_DIR=C:\\Qt\\6.8.0\\msvc2022_64\\lib\\cmake\\Qt6" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          echo "CMake configuration starting..."
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} -B ${{ github.workspace }}/build -S ${{ github.workspace }}/MyCAD
          
      - name: Build
        run: |
          echo "Build starting..."
          cmake --build ${{ github.workspace }}/build --config Release --parallel
